// 本機端到端驗證，不呼叫真正的 AI 或外部服務。
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');

(async () => {
  const browser = await chromium.launch({ headless: true, executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe' });
  const context = await browser.newContext({ viewport: { width: 1280, height: 900 } });
  // 此離線測試封鎖外部 CDN；首頁只驗證導覽連結，提供 Tailwind 設定容器。
  await context.addInitScript(() => { window.tailwind = { config: {} }; });
  await context.route('**/*', route => route.request().url().startsWith('http://127.0.0.1:8765') ? route.continue() : route.abort());
  const errors = [];
  context.on('page', page => page.on('pageerror', err => errors.push(err.message)));
  const page = await context.newPage();
  await context.request.post('http://127.0.0.1:8765/_test/reset');
  const artifacts = path.join(__dirname, '.artifacts');
  fs.mkdirSync(artifacts, { recursive: true });
  await page.goto('http://127.0.0.1:8765/index.html');
  await page.getByRole('link', { name: '教師管理' }).click();
  await page.locator('#adminToken').fill('wrong-password');
  await page.getByRole('button', { name: '登入', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('#connStatus').textContent.includes('不正確'));
  await page.locator('#adminToken').fill('preview-teacher-password');
  await page.getByRole('button', { name: '登入', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('#keyStatus').textContent.includes('已設定'));
  assert.equal(await page.locator('#rubricSelect option').count(), 2);
  await page.getByRole('button', { name: /讀取可用模型/ }).click();
  await page.waitForFunction(() => document.querySelector('#modelStatus').textContent.includes('已載入'));
  assert.equal(await page.locator('#modelName option').count(), 2);
  const example = path.join(__dirname, '../XML_Grader/esp32/Day(1)_Code(11).xml');
  await page.locator('#exampleFile').setInputFiles(example);
  await page.waitForFunction(() => document.querySelector('#exampleStatus').textContent.includes('已轉換'));
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: '🤖 依參考解答自動生成主題與規則', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('#suggestStatus').textContent.includes('已生成'));
  await page.locator('#testFile').setInputFiles(example);
  await page.getByRole('button', { name: '▶️ 試評這份作業', exact: true }).click();
  await page.locator('#testResult').waitFor({ state: 'visible' });
  assert.match(await page.locator('#testResult').textContent(), /86/);
  await page.locator('#theme').fill('LED 閃爍');
  await page.locator('#rules').fill('1. LED 亮滅（70 分）\n2. 等待時間（30 分）');
  await page.locator('#showScore').uncheck();
  await page.getByRole('button', { name: '💾 儲存設定', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('#saveStatus').textContent.includes('已儲存'));
  await page.screenshot({ path: path.join(artifacts, 'teacher-desktop.png'), fullPage: true });
  const student = await context.newPage();
  await student.goto('http://127.0.0.1:8765/student.html');
  await student.waitForFunction(() => document.querySelector('#connText').textContent.includes('可以開始'));
  assert.equal(await student.locator('#rubricSelect option').count(), 1);
  await student.locator('#studentId').fill('Browser-S001');
  await student.locator('#fileInput').setInputFiles(path.join(__dirname, '../XML_Grader/esp32/Day(1)_Code(11).xml'));
  await student.locator('#gradeBtn').click();
  await student.locator('#resultCard').waitFor({ state: 'visible' });
  assert.equal(await student.locator('#scoreNum').textContent(), '✓');
  assert.match(await student.locator('#logicText').textContent(), /數位輸出/);
  await student.screenshot({ path: path.join(artifacts, 'student-desktop.png'), fullPage: true });
  await page.getByRole('button', { name: '🔄 讀取學生成績', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('#subTable').textContent.includes('Browser-S001'));
  assert.match(await page.locator('#subTable').textContent(), /86/);
  await context.request.post('http://127.0.0.1:8765/_test/quota/on');
  await student.locator('#gradeBtn').click();
  await student.waitForFunction(() => document.querySelector('#status').textContent.includes('不計分'));
  assert.equal(await student.locator('#resultCard').isVisible(), false);
  await page.getByRole('button', { name: '🔄 讀取學生成績', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('#subStatus').textContent.includes('共 1 筆'));
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: path.join(artifacts, 'teacher-mobile.png'), fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.screenshot({ path: path.join(artifacts, 'teacher-mobile.png'), fullPage: true });
  await student.setViewportSize({ width: 390, height: 844 });
  assert.equal(await student.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await student.screenshot({ path: path.join(artifacts, 'student-mobile.png'), fullPage: true });
  await page.getByRole('button', { name: '登出', exact: true }).click();
  assert.equal(await page.locator('#adminToken').inputValue(), '');
  assert.equal(await page.locator('#subTable').textContent(), '');
  const stored = await page.evaluate(() => [Object.keys(localStorage), Object.keys(sessionStorage)]);
  assert.deepEqual(stored, [[], []]);
  assert.deepEqual(errors, []);
  await browser.close();
  console.log('PASS: login, models, XML conversion, AI rule suggestion, teacher trial, save, open-only tasks, hidden score, stored true score, quota without record, logout, mobile widths; no page errors.');
})().catch(error => { console.error(error); process.exit(1); });
